/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PrototypesCatalogLocalizationRouteImport } from './routes/prototypes.catalog-localization'
import { Route as PrototypesCatalogDesignRouteImport } from './routes/prototypes.catalog-design'
import { Route as PrototypesCatalogCopyRouteImport } from './routes/prototypes.catalog-copy'
import { Route as ProductsIdRouteImport } from './routes/products.$id'
import { Route as ApiProductsRouteImport } from './routes/api.products'
import { Route as ApiImageRouteImport } from './routes/api.image'
import { Route as ApiProductsIdRouteImport } from './routes/api.products.$id'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesCatalogLocalizationRoute =
  PrototypesCatalogLocalizationRouteImport.update({
    id: '/prototypes/catalog-localization',
    path: '/prototypes/catalog-localization',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrototypesCatalogDesignRoute = PrototypesCatalogDesignRouteImport.update({
  id: '/prototypes/catalog-design',
  path: '/prototypes/catalog-design',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypesCatalogCopyRoute = PrototypesCatalogCopyRouteImport.update({
  id: '/prototypes/catalog-copy',
  path: '/prototypes/catalog-copy',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIdRoute = ProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsRoute = ApiProductsRouteImport.update({
  id: '/api/products',
  path: '/api/products',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiImageRoute = ApiImageRouteImport.update({
  id: '/api/image',
  path: '/api/image',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiProductsIdRoute = ApiProductsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiProductsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/image': typeof ApiImageRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/prototypes/catalog-copy': typeof PrototypesCatalogCopyRoute
  '/prototypes/catalog-design': typeof PrototypesCatalogDesignRoute
  '/prototypes/catalog-localization': typeof PrototypesCatalogLocalizationRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/image': typeof ApiImageRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/prototypes/catalog-copy': typeof PrototypesCatalogCopyRoute
  '/prototypes/catalog-design': typeof PrototypesCatalogDesignRoute
  '/prototypes/catalog-localization': typeof PrototypesCatalogLocalizationRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/image': typeof ApiImageRoute
  '/api/products': typeof ApiProductsRouteWithChildren
  '/products/$id': typeof ProductsIdRoute
  '/prototypes/catalog-copy': typeof PrototypesCatalogCopyRoute
  '/prototypes/catalog-design': typeof PrototypesCatalogDesignRoute
  '/prototypes/catalog-localization': typeof PrototypesCatalogLocalizationRoute
  '/api/products/$id': typeof ApiProductsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/image'
    | '/api/products'
    | '/products/$id'
    | '/prototypes/catalog-copy'
    | '/prototypes/catalog-design'
    | '/prototypes/catalog-localization'
    | '/api/products/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/image'
    | '/api/products'
    | '/products/$id'
    | '/prototypes/catalog-copy'
    | '/prototypes/catalog-design'
    | '/prototypes/catalog-localization'
    | '/api/products/$id'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/image'
    | '/api/products'
    | '/products/$id'
    | '/prototypes/catalog-copy'
    | '/prototypes/catalog-design'
    | '/prototypes/catalog-localization'
    | '/api/products/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiImageRoute: typeof ApiImageRoute
  ApiProductsRoute: typeof ApiProductsRouteWithChildren
  ProductsIdRoute: typeof ProductsIdRoute
  PrototypesCatalogCopyRoute: typeof PrototypesCatalogCopyRoute
  PrototypesCatalogDesignRoute: typeof PrototypesCatalogDesignRoute
  PrototypesCatalogLocalizationRoute: typeof PrototypesCatalogLocalizationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/catalog-localization': {
      id: '/prototypes/catalog-localization'
      path: '/prototypes/catalog-localization'
      fullPath: '/prototypes/catalog-localization'
      preLoaderRoute: typeof PrototypesCatalogLocalizationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/catalog-design': {
      id: '/prototypes/catalog-design'
      path: '/prototypes/catalog-design'
      fullPath: '/prototypes/catalog-design'
      preLoaderRoute: typeof PrototypesCatalogDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototypes/catalog-copy': {
      id: '/prototypes/catalog-copy'
      path: '/prototypes/catalog-copy'
      fullPath: '/prototypes/catalog-copy'
      preLoaderRoute: typeof PrototypesCatalogCopyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$id': {
      id: '/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof ProductsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products': {
      id: '/api/products'
      path: '/api/products'
      fullPath: '/api/products'
      preLoaderRoute: typeof ApiProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/image': {
      id: '/api/image'
      path: '/api/image'
      fullPath: '/api/image'
      preLoaderRoute: typeof ApiImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/products/$id': {
      id: '/api/products/$id'
      path: '/$id'
      fullPath: '/api/products/$id'
      preLoaderRoute: typeof ApiProductsIdRouteImport
      parentRoute: typeof ApiProductsRoute
    }
  }
}

interface ApiProductsRouteChildren {
  ApiProductsIdRoute: typeof ApiProductsIdRoute
}

const ApiProductsRouteChildren: ApiProductsRouteChildren = {
  ApiProductsIdRoute: ApiProductsIdRoute,
}

const ApiProductsRouteWithChildren = ApiProductsRoute._addFileChildren(
  ApiProductsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiImageRoute: ApiImageRoute,
  ApiProductsRoute: ApiProductsRouteWithChildren,
  ProductsIdRoute: ProductsIdRoute,
  PrototypesCatalogCopyRoute: PrototypesCatalogCopyRoute,
  PrototypesCatalogDesignRoute: PrototypesCatalogDesignRoute,
  PrototypesCatalogLocalizationRoute: PrototypesCatalogLocalizationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
